components/Footer/index.tsx
=> updating social media and adding year in footer

pages/api/createDailyUpdate.ts, pages/porch.tsx
After creating a daily update, sending back response and updating the daily list
=> [bug] Send a Proper Response

components/Posts/PostsGrid/index.tsx, lib/posts-lib/index.ts, yarn.lock
=> [Bug] Sort Feature Post by Date

pages/porch.tsx
=> [Bug] Fixing Porch page

components/ContactForm/index.tsx, components/Forms/NewResourceForm/index.tsx, pages/api/createDailyUpdate.ts, pages/freesource.tsx, pages/porch.tsx
I moved voting to be handled by serverless nextjs functions
=> [ Improvement ] - Vote Call moved to backend 

pages/porch.tsx
Sorting Porch Page Updates by date
Adding proper types to the functions
=> Sorting Daily updates by time 

pages/porch.tsx
Improve Page: 
Improve page
- style 
- readability
=> [Style] Porch Page 

components/Layout/MainNavigation/mobileView.tsx, components/Layout/MainNavigation/navigation.module.css
=> Fixed userNameDisplay

components/Layout/MainNavigation/index.tsx, components/VideoElements/VideoCard/card.tsx, lib/videoHelper.tsx, pages/contact.tsx, tailwind.config.js
-Footer at Contact page fixed
-Locked videos for users that are not logged in and email-verified
-Added notification when hover over video if user is not logged in
-Added link to notification that redirects to Login page
=> Auth videos

components/HeadBasePage/index.tsx, components/Posts/Post/PostContent/index.tsx, lib/constants/index.ts, lib/types/index.ts, pages/_app.tsx, pages/contact.tsx, pages/freesource.tsx, pages/porch.tsx, pages/videos.tsx
Updating for SEO on the website
=> SEO updates

posts/clousers-js.md, posts/currying-javascript.md
=> WIP: API supa base integration

components/PorchElements/PorchDailyUpdate/index.tsx, components/PorchElements/PorchHeader/index.tsx, package.json, yarn.lock
- Added new like button
- Added restructured update card 
- created border and bg for source and email to separate from added content 
- added underline hover effect to source and email to show it is clickable 
- Made Changes to daily update header 
- switched the location of the formatted date to the bottom and changed the order.
=> Added styles to daily update porch page

.eslintrc.json, components/Categorysearch/index.tsx, components/Posts/BlogMenuCat/index.tsx, lib/hooks/useLocalStorage.ts
add custom hook useLocalStorage to BlogManuCat and Categorysearch components
=> add custom hook useLocalStorage

components/Categorysearch/index.tsx, components/Posts/Post/PostHeader/index.tsx, pages/category/[...category].tsx
Changes in components/Posts/PostHeader.index.tsx , line 19: 
-text from "Blog" to "Category";
-updated anchor tag - href to navigate to selected Blog's category;
-updated title to also display category instead if "Blog Page";
=> Fixing path for selected Blog

components/CategoryFilter/index.tsx, components/Layout/MainNavigation/index.tsx, lib/constants/index.ts
Refactored categories on Free Resources Page to have the same look and functionality as categories on Blog Page.
=> Refactored menu items in Free Resources

components/Comments.tsx, pages/api/postComments.ts
Post Comments API endpoint for sending the comments to supabase
=> post comments API

components/PorchElements/PorchForm/index.tsx, pages/porch.tsx
Changed porch form styles to match free resources/new resource form. also added blur effect when porch form window is opened
=> PorchForm style changed

.gitignore, components/Auth/Login/index.tsx, components/Comments.tsx, pages/auth/[authid].tsx
On Free Resources page add comment form is now hidden when user isn't logged in.
=> hide comments form input when user is not logged in

components/Alerts/ErrorAlertMsg/index.tsx, components/Auth/Login/index.tsx, components/Auth/SignIn.tsx
Refactor the code for SignIn component.
Replace useState hook with useRef hook for handling states of User Email and User Password.
Get familiar with useRef Hook - its purpose and use cases.
=> Refactor/useState to useRef in SignIn component

components/PorchElements/PorchHeader/index.tsx, components/PorchElements/PorchUserDataForm/index.tsx, components/Quotes.tsx, pages/porch.tsx
Add close button for PorchUserDataForm component.
Create and add Quotes component to porch page.
=> add close button for porchuserdataform and quotes component

components/Auth/CreateAccount/index.tsx, components/Auth/Login/index.tsx, components/Auth/LoginPopup/index.tsx, components/Auth/ResetPassword/index.tsx, components/Comments.tsx, components/FreeSourcesList/FreeSource/index.tsx, components/FreeSourcesList/index.tsx, components/Layout/CardsLayout/index.tsx, components/Layout/MainNavigation/index.tsx, components/Layout/MainNavigation/mobileView.tsx, components/LearningSources/index.tsx, components/PorchElements/PorchDailyUpdate/index.tsx, components/PorchElements/PorchHeader/index.tsx, components/PorchElements/PorchInteractivity/index.tsx, lib/helpers/categoryTags.tsx
Created login modal for porch-check your stats button(when clicked login modal shows).
Implemented this wherever user is asked to be logged in. 
Created component in Layout/CardsLayout for styling cards on Porch Page and FreeResources Page, that is reusable. Still need to work on button on FreeRes page and to do some additional styling. 
How to Test? 
- .....
=> Login/popup window and FreeResource styling

Types/Navigation/index.tsx, components/DropDown/index.tsx, components/Layout/MainNavigation/index.tsx, components/Layout/MainNavigation/navigation.module.css, components/Posts/BlogDropDown/index.tsx, components/Posts/BlogMenuCat/index.tsx, lib/posts-lib/index.ts, pages/_app.tsx, pages/api/categories.ts, pages/index.tsx
Creating drop down component for Main Navigation - blog categories
=> Drop Down Menu for Blogs

components/Comments.tsx, components/CommentsPopup/index.tsx, components/Layout/MainNavigation/mobileView.tsx, components/Layout/MainNavigation/navigation.module.css, components/Subscribe/index.tsx, components/porchComments.tsx
Changed Navigation bar view Tablet size screens, now Subscribe now button and Burger menu are inly visible.
=> Desktop view changes for Navigation bar

components/PorchElements/PorchDailyUpdate/index.tsx
=> fixing update like button

components/PorchElements/PorchDailyUpdate/index.tsx, pages/api/createDailyUpdate.ts
Fixed path to excellent row in supabase.
=> fixed like button on porch page

components/PorchElements/PorchDailyUpdate/index.tsx, package.json
=> Upgrade Slavo.io

components/Layout/CardsLayout/index.tsx
=> Fix - Missing Date

components/PorchElements/PorchUserDataForm/Calendar/index.tsx
Added background color for current week on calendar charts. This is calendar that track user activity on porch page.
=> background color for current week add

components/PorchElements/PorchWeeklyGoalForm/index.tsx
Fix the bug so user can chose weekly goal based on remaining day of the week.
=> fix weekly goal based on current day

components/Footer/index.tsx
Ensure when user click on linkedin link it opens in new tab
=> add target atribute inside linkdin a tag

components/ContactForm/index.tsx, components/ContactForm/notificationTest.tsx, components/Notification/notification.module.css, lib/notificationStatus/index.tsx, pages/contact.tsx, tailwind.config.js
Contact Us Form updates:  
- Checkbox now working properly 
- Form being reseted after successfully submitted 
- Notification messages re-styled 
- Alert messages re-styled
- Added responsiveness for different screen sizes
=> Fixing Contact Us form

pages/porch.tsx
In needs for fetching fresh data on user request, function on Porch page changed from SSG to SSR.
=> change fetch function from SSG to SSR

components/Auth/LoginPopup/index.tsx, components/Auth/ResetPassword/index.tsx, components/Auth/ResetPasswordRedirect/index.tsx, pages/login.tsx, pages/password-reset-success.tsx
Created redirect page when user click to reset password and email been sent to him.
=> create password-reset-sucess page

components/Categorysearch/index.tsx, components/Posts/BlogDropDown/index.tsx, components/Posts/BlogMenuCat/index.tsx, components/Posts/BlogPosts/index.tsx, lib/hooks/useCategoryHook.ts, pages/blog/index.tsx
Search Category Bar is now on the same category as Drop Down Menu selected category.  The titles and categories match, and also I have removed the category tags that were on slug pages, there were always 2 tags - ALL and selected category tag that had no functionality (removed them with conditional rendering in Blog page).
=> Fixed the Search Category Bar 

components/Auth/ResetPassword/index.tsx, pages/api/check-user-email.ts
Fixed issue so user can't click on button unless input field is properly filed out.
=> fix issue with empty field for password input
